/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/thetruescruture.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/thetruescruture.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.37, 17.83, -6.221]} rotation={[Math.PI, -0.347, Math.PI]} scale={[1.769, 1.386, 1.769]}>
        <mesh geometry={nodes.Icosphere042.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Icosphere042_1.geometry} material={materials['Material.003']} />
      </group>
    </group>
  )
}

useGLTF.preload('/thetruescruture.glb')
