spring.application.name=Av

spring.datasource.url=jdbc:mysql://143.106.241.4:3306/cl204177?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=cl204177
spring.datasource.password=cl*04062009
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

server.port=8081
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.physical_naming_strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
spring.jpa.open-in-view=false

spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.idle-timeout=300000
builder.secret=Paodequeijonasanduicheira