export const GOOGLE_FONTS = {
  "Sem serifa": [
    "Roboto", "Open Sans", "Lato", "Montserrat", "Poppins", "Inter",
    "Nunito", "Raleway", "Josefin Sans", "Work Sans", "Rubik",
    "Manrope", "DM Sans", "Mulish", "Karla",
    "Space Grotesk", "Sora", "Outfit", "Plus Jakarta Sans", "Urbanist",
    "Comfortaa", "Quicksand", "Jost", "Epilogue", "Baloo 2",
    "Figtree", "Albert Sans", "Hanken Grotesk", "Instrument Sans",
    "Hind", "Spline Sans",
  ],
  "Serifada": [
    "Playfair Display", "Merriweather", "Lora", "PT Serif",
    "Cormorant Garamond", "Libre Baskerville", "Crimson Text",
    "Bitter", "EB Garamond",
    "Cinzel", "Cinzel Decorative", "Fraunces", "Spectral",
    "DM Serif Display", "Vollkorn", "Frank Ruhl Libre", "Prata", "Alegreya",
    "Newsreader", "Literata", "Instrument Serif",
  ],
  "Display": [
    "Bebas Neue", "Oswald", "Anton", "Righteous", "Bungee",
    "Fredoka", "Archivo Black", "Passion One",
    "Lobster", "Alfa Slab One", "Bangers", "Bevan", "Black Ops One",
    "Bowlby One", "Luckiest Guy", "Monoton", "Russo One", "Titan One",
    "Ultra", "Rammetto One", "Abril Fatface",
    "UnifrakturMaguntia", "Creepster", "Bungee Spice", "Nabla",
    "Chewy", "Fascinate", "Nova Round", "Nova Square", "Special Elite",
    "Bricolage Grotesque",
  ],
  "Manuscrita": [
    "Pacifico", "Dancing Script", "Caveat", "Sacramento",
    "Great Vibes", "Satisfy", "Shadows Into Light", "Kalam",
    "Alex Brush", "Amatic SC", "Architects Daughter", "Homemade Apple",
    "Indie Flower", "Kaushan Script", "Marck Script", "Permanent Marker",
    "Gloria Hallelujah", "Gochi Hand", "Cedarville Cursive", "Patrick Hand",
    "Reenie Beanie", "Yellowtail", "Parisienne", "Pinyon Script",
    "Italianno", "Just Another Hand",
    "Handlee", "Neucha", "Walter Turncoat",
  ],
  "Monoespaçada": [
    "Roboto Mono", "Space Mono", "JetBrains Mono", "Fira Code",
    "IBM Plex Mono", "Source Code Pro",
    "Inconsolata", "Cutive Mono", "Azeret Mono",
    "VT323", "Press Start 2P", "Silkscreen", "Syne Mono",
  ],
};